# CREATE A FILE
File.open('text.txt', 'r+') do |file|
  puts file.readline()
  file.write("mo cover eh")
end

# CREATE A FILE
# File.open('index.html', 'w') do |file|
#   file.write("<h1> Autogenerated </h1>")
# end

# WRITE TO A FILE
# File.open('text.txt', 'w') do |file|
#   file.write("Philip, Doctor")
# end

# APPEND TO A FILE
# File.open('text.txt', 'a') do |file|
#   file.write("Philip, Doctor")
# end

# READ FROM A FILE
# File.open('text.txt', 'r') do |file|
# puts file.read()
# end